### ISSUE TITLE
怎么用啊，大哥

### ISSUE THREAD

**Issue by Chadwuo** [zhaobangyu/NSIS#1]
![QQ截图20210113172812](https://user-images.githubusercontent.com/41413559/104433238-d62a9d00-55c4-11eb-8f8e-b73572e674c0.png)
按照这个步骤执行下来，运行build-qqmusic-nozip.bat，不成功啊 
在此之前没接触过NSIS脚本。能否抽空帮我一下，给您磕头了

**Comment by Chadwuo** [comment]
操作步骤：
简体包打包步骤
1、打开AppCode\您的项目目录\app\setup.nsi 脚本
2、修改 APP_FILE_DIR 变量(对应打包应用的文件目录，改成你电脑上对应的目录)
3、修改 APP_FILE_COUNT 变量（应用程序打包的文件数量）
4、执行build-您的项目-nozip.bat脚本即可
5、打包后的文件在Output目录下

**Comment by zhaobangyu** [comment]
报错信息截图发我看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaobangyu/NSIS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 下午5:30
收件人:&nbsp;"zhaobangyu/NSIS"<NSIS@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhaobangyu/NSIS] 怎么用啊，大哥 (#1)





 

 按照这个步骤执行下来，运行build-qqmusic-nozip.bat，不成功啊
 在此之前没接触过NSIS脚本。能否抽空帮我一下，给您磕头了

**Comment by zhaobangyu** [comment]
你加我QQ吧，可以帮你快速解决问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "❤将来,大不同"                                                                                    <763098346@qq.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 下午5:32
收件人:&nbsp;"zhaobangyu/NSIS"<reply@reply.github.com&gt;;

主题:&nbsp;回复：[zhaobangyu/NSIS] 怎么用啊，大哥 (#1)



报错信息截图发我看看




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zhaobangyu/NSIS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 下午5:30
收件人:&nbsp;"zhaobangyu/NSIS"<NSIS@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhaobangyu/NSIS] 怎么用啊，大哥 (#1)





 

 按照这个步骤执行下来，运行build-qqmusic-nozip.bat，不成功啊
 在此之前没接触过NSIS脚本。能否抽空帮我一下，给您磕头了
