### ISSUE TITLE
NSIS能把运行环境打包进去吗？安装时不再需要联网下运行环境

### ISSUE THREAD

**Issue by Lj-dog** [zhaobangyu/NSIS#10]
没搜出来

**Comment by zhaobangyu** [comment]
可以的，参考安装完成后，运行执行程序的逻辑。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaobangyu/NSIS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月18日(星期三) 下午2:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [zhaobangyu/NSIS] NSIS能把运行环境打包进去吗？安装时不再需要联网下运行环境 (Issue #10)





 
Closed #10 as completed.
